
GET http://localhost:8080/api/v1/departament?name=alexis

###

GET http://localhost:8080/api/v1/departament/35240eb9-4923-45fe-a0c9-5494b14b760e

###

POST http://localhost:8080/api/v1/departament
content-type: application/json

{
    "name": "Departament {{$randomInt 100 1000}}-{{$randomInt 100 1000}}"
}

###

DELETE  http://localhost:8080/api/v1/departament/8ac2b078-e60d-4bce-90aa-674706e77a68