GET http://localhost:8080/api/v1/activity

###

POST http://localhost:8080/api/v1/activity
content-type: application/json

{
    "action_plan_id":"14327a50-73e3-4740-8613-376dba35542e",
    "name": "activity {{$randomInt 100 1000}}-{{$randomInt 100 1000}}",
    "annex_id": ""
}

###
