GET http://localhost:8080/api/v1/career

###

GET http://localhost:8080/api/v1/career/8620711d-f5d3-4707-97fe-8b15ce422bd7

###

POST http://localhost:8080/api/v1/career
content-type: application/json

{
    "name": "Carrera {{$randomInt 100 1000}}-{{$randomInt 100 1000}}",
    "departament_id":"92c462ba-59f8-47d3-b386-338f7978de0b"
}

###

DELETE  http://localhost:8080/api/v1/career/1ec1187b-f89f-4e06-bce8-1a39b626a714