GET http://localhost:8080/api/v1/activity-institutional-mentoring-program

###

POST http://localhost:8080/api/v1/activity-institutional-mentoring-program
content-type: application/json

{
    "name": "activity-imp {{$randomInt 100 1000}}-{{$randomInt 100 1000}}",
    "straegy_id": "b2562db2-18bc-4ee3-a9b9-7bceb81151f4"
}

###

PUT http://localhost:8080/api/v1/activity-institutional-mentoring-program/78edcb30-bdb7-481e-aed2-60a489e62f75
content-type: application/json

{
    "name": "activity-imp {{$randomInt 100 1000}}-{{$randomInt 100 1000}}",
    "straegy_id": "b2562db2-18bc-4ee3-a9b9-7bceb81151f4"
}