
GET http://localhost:8080/api/v1/profile?size=2&name=5&email=correo&page=1

###

GET http://localhost:8080/api/v1/profile/078d42d3-b0c9-4dc2-8533-7aff5c212c30

###

POST http://localhost:8080/api/v1/profile
content-type: application/json

{
    "name": "name-{{$randomInt 100 1000}}",
    "email": "correo{{$randomInt 100 1000}}@corrreo.com",
    "password":"ultrasecret" 
}