
GET http://localhost:8080/api/v1/student

###
POST http://localhost:8080/api/v1/student
content-type: application/json

{
    "control_number": "{{$randomInt 100000 1000000}}",
    "profile_id": "b6a0fa99-723f-4d0a-8f84-828ce9c0c419"
}

###
PUT http://localhost:8080/api/v1/student/6f97cc7b-8e75-4e55-882e-422929a98f90
content-type: application/json

{
    "control_number": "{{$randomInt 100000 1000000}}",
    "profile_id": "b6a0fa99-723f-4d0a-8f84-828ce9c0c419"
}