GET http://localhost:8080/api/v1/syllabus

###

GET http://localhost:8080/api/v1/syllabus/5121d275-d93b-4bea-b5a9-e633e5899d55

###

POST http://localhost:8080/api/v1/syllabus
content-type: application/json

{
    "code": "AQWSDE-{{$randomInt 100 1000}}",
    "start_date": "2020-01-22",
    "end_date":"2020-01-22",
    "career_id" : "bbd15c2c-18c6-4d41-bd41-b2eb89e6e6da"
}

###

PUT http://localhost:8080/api/v1/syllabus/5121d275-d93b-4bea-b5a9-e633e5899d55
content-type: application/json

{
    "code": "AQWSDE-{{$randomInt 100 1000}}",
    "start_date": "2020-01-22",
    "end_date":"2020-01-22",
    "career_id" : "bbd15c2c-18c6-4d41-bd41-b2eb89e6e6da"
}

###

DELETE  http://localhost:8080/api/v1/syllabus/5121d275-d93b-4bea-b5a9-e633e5899d55
